[build]
command = "npm run build"
publish = "build"

[functions]
directory = "functions"

[[redirects]]
from = "/"
to = "/docs/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/docs/index.html"
status = 200
